### ISSUE TITLE
Web Space Issues

### ISSUE THREAD

**Issue by PiperBaron** [PiperBaron/PoetrybyPiperBaron#9]
I just tried to upload the current HTML, CSS, and JS files I have for my website in my NewtFire web space, and I'm having some issues. The site isn't updating with my additions, and when I attempt to access it without the HTTPS, I get an error saying I don' have permission. 

I'm sure this is an easy fix, but I'd like to have the site up and running soon, so I can start linking to it!

**Comment by ebeshero** [comment]
Hi @PiperBaron ! I did not set up https yet for your sites yet. Try just the http address for now! We can configure https when we meet…

**Comment by ebeshero** [comment]
Also, looking at your directory, home.html does not work for the root page of the site. You need a file named index.html. I do not recommend filing your HTML files in an internal “HTML” directory.

**Comment by PiperBaron** [comment]
@ebeshero You're right! It wasn't working, because I named it "home.html". At least without the HTTPS, the site is now functioning.
